language: node_js
node_js:
  - "0.12"
  - "0.10"
services: 
  - postgresql
  - mongodb
  - mysql
  - redis-server
addons:
  postgresql: "9.3"
env:
  - DB_USER=postgres DB_PASS=''
before_script:
  - npm install balderdashy/waterline
  - psql -c 'create database sailspg;' -U postgres
  - mysql -e 'create database sails_mysql;'
